/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import utils.FormUtils;
import utils.TableUtils;
import controller.AdminController;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import model.Admin;

import utils.MessageUtil;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Acer
 */
public class AdminView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminView.class.getName());
     private int selectedUserId = 0;
    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
        setLocationRelativeTo(null);
        tampilDataAdmin();
        TableUtils.setTableStyle(table_admin);
    }

    private void tampilDataAdmin() {

        DefaultTableModel model
                = (DefaultTableModel) table_admin.getModel();

        model.setRowCount(0);

        AdminController adminController
                = new AdminController();

        ArrayList<Admin> list
                = adminController.getAllAdmin();

        for (Admin admin : list) {

            Object[] row = {
                admin.getIdAdmin(),
                admin.getUsername(),
                admin.getName(),
                admin.getJabatan()

            };

            model.addRow(row);
        }
    }

    private void resetForm() {

        id_admin.setText("");

        username.setText("");

        name.setText("");

        password.setText("");

        jabatan.setSelectedIndex(0);

        table_admin.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_admin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jabatan = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        id_admin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Admin");
        setUndecorated(true);

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setText("Kelola Admin");

        table_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Admin", "Username", "Nama", "Jabatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_admin.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        table_admin.setShowGrid(true);
        table_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_adminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_admin);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Jabatan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password");

        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(this::usernameActionPerformed);
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.addActionListener(this::nameActionPerformed);

        jabatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin Utama", "Pustakawan", "Staff" }));
        jabatan.addActionListener(this::jabatanActionPerformed);

        password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_add.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add.setForeground(java.awt.Color.white);
        btn_add.setText("Add");
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(this::btn_addActionPerformed);

        btn_update.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setForeground(java.awt.Color.white);
        btn_update.setText("Update");
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(this::btn_updateActionPerformed);

        btn_delete.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete.setForeground(java.awt.Color.white);
        btn_delete.setText("Delete");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        reset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setForeground(java.awt.Color.white);
        reset.setText("Reset");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(this::resetActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 153, 153));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText("back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ID");

        id_admin.setEditable(false);
        id_admin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(156, 156, 156))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)))
                        .addComponent(btnBack)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btn_add)
                .addGap(24, 24, 24)
                .addComponent(btn_update)
                .addGap(24, 24, 24)
                .addComponent(btn_delete)
                .addGap(26, 26, 26)
                .addComponent(reset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(id_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(reset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        FormUtils.openForm(this, new AdminDashboardView());
    }//GEN-LAST:event_btnBackMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        AdminController adminController = new AdminController();
        String usernameValue
                = username.getText();
        String nameValue
                = name.getText();

        String passwordValue
                = String.valueOf(
                        password.getPassword()
                );
        String hashedPassword =
            BCrypt.hashpw(
                    passwordValue,
                    BCrypt.gensalt()
            );

        String jabatanValue
                = jabatan.getSelectedItem()
                        .toString();

        if (usernameValue.isEmpty()
                || nameValue.isEmpty()
                || passwordValue.isEmpty()) {

            MessageUtil.warning(
                    this,
                    "Lengkapi semua data"
            );

            return;
        }

        Admin admin = new Admin();
        
        admin.setUsername(
                usernameValue
        );

        admin.setName(
                nameValue
        );

        admin.setPassword(
                hashedPassword
        );
        
        admin.setJabatan(
                jabatanValue
        );

      
        
        boolean result
                = adminController.tambahAdmin(
                        admin
                );

        if (result) {

            MessageUtil.success(
                    this,
                    "Admin berhasil ditambahkan"
            );

            tampilDataAdmin();

            resetForm();

        } else {

            MessageUtil.error(
                    this,
                    "Gagal menambahkan admin"
            );
        }

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if (id_admin.getText().isEmpty()) {

            MessageUtil.warning(
                    this,
                    "Pilih data admin terlebih dahulu"
            );

            return;
        }
        AdminController adminController
                = new AdminController();

        Admin admin = new Admin();

        admin.setIdAdmin(
                Integer.parseInt(
                        id_admin.getText()
                )
        );
        admin.setUserId(selectedUserId);
        admin.setUsername(
                username.getText()
        );

        admin.setName(
                name.getText()
        );

        String hashedPassword =
            BCrypt.hashpw(
                    String.valueOf(
                        password.getPassword()
                ),
                    BCrypt.gensalt()
            );
        admin.setPassword(
                hashedPassword
        );

        admin.setJabatan(
                jabatan.getSelectedItem()
                        .toString()
        );
        
        

        boolean result
                = adminController.updateAdmin(
                        admin
                );

        if (result) {

            MessageUtil.success(
                    this,
                    "Data admin berhasil diupdate"
            );

            tampilDataAdmin();

            resetForm();

        } else {

            MessageUtil.error(
                    this,
                    "Gagal update admin"
            );
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (id_admin.getText().isEmpty()) {

            MessageUtil.warning(
                    this,
                    "Pilih data admin terlebih dahulu"
            );

            return;
        }

        int confirm
                = MessageUtil.confirm(
                        this,
                        "Hapus admin ini?"
                );

        if (confirm
                != JOptionPane.YES_OPTION) {

            return;
        }

        int userId
                = selectedUserId;

        AdminController adminController
                = new AdminController();

        boolean result
                = adminController.deleteAdmin(
                        userId
                );

        if (result) {

            MessageUtil.success(
                    this,
                    "Admin berhasil dihapus"
            );

            tampilDataAdmin();

            resetForm();

        } else {

            MessageUtil.error(
                    this,
                    "Gagal menghapus admin"
            );
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void table_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_adminMouseClicked
        // TODO add your handling code here:
         int row
            = table_admin.getSelectedRow();

    if (row < 0) {

        return;
    }

    int idAdmin
            = Integer.parseInt(
                    table_admin.getValueAt(
                            row,
                            0
                    ).toString()
            );
     
    AdminController adminController
            = new AdminController();

    Admin admin
            = adminController.getAdminById(
                    idAdmin
            );
    
    if (admin != null) {

        selectedUserId
                = admin.getUserId();
       
        id_admin.setText(
                String.valueOf(
                        admin.getIdAdmin()
                )
        );
        username.setText(
                admin.getUsername()
        );

        name.setText(
                admin.getName()
        );

        jabatan.setSelectedItem(
                admin.getJabatan()
        );
    }
    }//GEN-LAST:event_table_adminMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_resetActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped

    }//GEN-LAST:event_usernameKeyTyped

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        AdminController adminController = new AdminController();
        String usernameValue
                = username.getText();
        boolean usernameReady = adminController.handlingDuplicateUsername(usernameValue);
        if(usernameReady){
             MessageUtil.warning(
                    this,
                    "Username sudah digunakan"
            );
             username.setText("");
             username.requestFocus();
             return;
        }
        
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        name.requestFocus();
    }//GEN-LAST:event_usernameActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        password.requestFocus();
    }//GEN-LAST:event_nameActionPerformed

    private void jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jabatanActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new AdminView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField id_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jabatan;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JTable table_admin;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
