/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;
import utils.FormUtils;
import controller.BukuController;
import java.util.ArrayList;
import model.Buku;
import controller.PeminjamanController;
import model.Peminjaman;
import javax.swing.table.DefaultTableModel;
import model.Anggota;
import controller.AnggotaController;
import utils.MessageUtil;
import java.time.LocalDate;
import java.text.SimpleDateFormat;
import java.util.Date;
import utils.TableUtils;
import javax.swing.JOptionPane;
/**
 *
 * @author Acer
 */
public class BorrowView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BorrowView.class.getName());
    int selectedId = 0;
    /**
     * Creates new form BorrowView
     */
    public BorrowView() {
        initComponents();
        loadBuku();
        loadData();
        TableUtils.setTableStyle(table_pinjam);
        loadAnggota();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        tanggalPinjam.setText(sdf.format(new Date()));
        
        status.removeAllItems();
        status.addItem("--Pilih Status Peminjaman--");
        status.addItem("dipinjam");
        status.addItem("dikembalikan");
    }
    private void loadData(){
        DefaultTableModel model
                = (DefaultTableModel) table_pinjam.getModel();
        model.setRowCount(0);
        PeminjamanController peminjamanController = new PeminjamanController();
        ArrayList<Peminjaman> list = peminjamanController.getAllPeminjaman();
        for(Peminjaman pinjam : list){
            Object[] row = {
                pinjam.getIdPinjam(),
                pinjam.getNama(),
                pinjam.getJudulBuku(),
                pinjam.getTanggalPinjam(),
                pinjam.getLamaPeminjaman(),
                pinjam.getTanggalKembali(),
                pinjam.getStatus()
            };
            model.addRow(row);
        }
    }
    private void loadBuku(){
        BukuController bukuController = new BukuController();
        ArrayList<Buku> list = bukuController.getAllBuku();
        cmbBuku.removeAllItems();
        cmbBuku.addItem("-- Pilih Buku --");
        
        for(Buku buku : list){
            cmbBuku.addItem(buku.getJudulBuku());
        }
    }
    
    private void loadAnggota(){
        AnggotaController anggotaController = new AnggotaController();
        ArrayList<Anggota> list = anggotaController.getAllMember();
        cmbAnggota.removeAllItems();
        cmbAnggota.addItem("--Pilih Anggota--");
        
        for(Anggota anggota : list){
            cmbAnggota.addItem(anggota.getUsername());
        }
    }
    
    private void resetForm(){
        idPinjam.setText("");
        cmbAnggota.setSelectedIndex(0);
        cmbBuku.setSelectedIndex(0);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        tanggalPinjam.setText(sdf.format(new Date()));
        lamaPinjam.setText("");
        status.setSelectedIndex(0);
        
        cmbAnggota.setEnabled(true);
        cmbBuku.setEnabled(true);
        lamaPinjam.setEditable(true);
    }
    private String hitungJangkaPinjam(){

        int lama = Integer.parseInt(
                lamaPinjam.getText()
        );

        LocalDate tanggal_pinjam
                = LocalDate.parse(
                        tanggalPinjam.getText()
                );

        LocalDate tanggalKembali
                = tanggal_pinjam.plusDays(lama);

        String tgl_kembali = tanggalKembali.toString();
        return tgl_kembali;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idPinjam = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tanggalPinjam = new javax.swing.JTextField();
        lamaPinjam = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pinjam = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        cmbBuku = new javax.swing.JComboBox<>();
        cmbAnggota = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Borrowing");
        setUndecorated(true);

        jPanel1.setBackground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Judul Buku");

        idPinjam.setEditable(false);
        idPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idPinjam.setToolTipText("Enter your username");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 153, 153));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText("back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("ID");

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setText("Kelola Peminjaman");

        tanggalPinjam.setEditable(false);
        tanggalPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tanggalPinjam.setToolTipText("Enter your username");

        lamaPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lamaPinjam.setToolTipText("Enter your username");
        lamaPinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamaPinjamKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Jangka Waktu Pinjam (Hari)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tanggal Pinjam");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Username Anggota");

        update.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setForeground(java.awt.Color.white);
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(this::updateActionPerformed);

        reset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setForeground(java.awt.Color.white);
        reset.setText("Reset");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(this::resetActionPerformed);

        delete.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setForeground(java.awt.Color.white);
        delete.setText("Delete");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(this::deleteActionPerformed);

        add.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add.setForeground(java.awt.Color.white);
        add.setText("Add");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(this::addActionPerformed);

        table_pinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usernama Peminjam", "Judul Buku", "Tanggal Pinjam", "Lama Peminjaman (Hari)", "Tanggal Kembali", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_pinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_pinjam.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        table_pinjam.setShowGrid(true);
        table_pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pinjam);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Status");

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cmbAnggota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123)
                        .addComponent(btnBack)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbBuku, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(idPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(cmbAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(77, 77, 77))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lamaPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cmbAnggota))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cmbBuku))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(reset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        FormUtils.openForm(this, new AdminDashboardView());
    }//GEN-LAST:event_btnBackMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(cmbAnggota.getSelectedIndex() == 0){
            MessageUtil.warning(this, "Pilih Anggota Terlebih Dahulu");
            cmbAnggota.requestFocus();
            return;
        }
        else if(cmbBuku.getSelectedIndex() == 0){
            MessageUtil.warning(this, "Pilih Buku Terlebih Dahulu");
            cmbBuku.requestFocus();
            return;
        }
        else if(lamaPinjam.getText().isEmpty()){
            MessageUtil.warning(this, "Jangka Waktu Pinjam Harus Diisi");
            lamaPinjam.requestFocus();
            return;
        }
  
        
        Peminjaman peminjaman = new Peminjaman();
        peminjaman.setIdPinjam(Integer.parseInt(idPinjam.getText()));
        peminjaman.setStatus(status.getSelectedItem().toString());
        
        PeminjamanController peminjamanCon = new PeminjamanController();
        boolean hasil = peminjamanCon.updateStatus(peminjaman.getIdPinjam(), peminjaman.getStatus());
        if(hasil){
            loadData();
            MessageUtil.success(this, "Berhasil Mengubah Status");
            resetForm();  
    }else{
            MessageUtil.success(this, "Gagal Mengubah Status");
            resetForm(); 
        }
    }//GEN-LAST:event_updateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(cmbAnggota.getSelectedIndex() == 0){
            MessageUtil.warning(this, "Pilih Anggota Terlebih Dahulu");
            cmbAnggota.requestFocus();
            return;
        }
        else if(cmbBuku.getSelectedIndex() == 0){
            MessageUtil.warning(this, "Pilih Buku Terlebih Dahulu");
            cmbBuku.requestFocus();
            return;
        }
        else if(lamaPinjam.getText().isEmpty()){
            MessageUtil.warning(this, "Jangka Waktu Pinjam Harus Diisi");
            lamaPinjam.requestFocus();
            return;
        }
        else if (status.getSelectedIndex() == 0){
            MessageUtil.warning(this, "Pilih Status Peminjaman");
            status.requestFocus();
            return;
        }
        AnggotaController anggotaController = new AnggotaController();
        BukuController bukuController = new BukuController();
        
        int id_anggota = anggotaController.getIdByUsername(cmbAnggota.getSelectedItem().toString());
        int id_buku = bukuController.getIdByJudul(cmbBuku.getSelectedItem().toString());
        String tanggal_kembali = hitungJangkaPinjam();
        
        Peminjaman peminjaman = new Peminjaman();
        peminjaman.setIdAnggota(id_anggota);
        peminjaman.setIdBuku(id_buku);
        peminjaman.setTanggalPinjam(tanggalPinjam.getText());
        peminjaman.setLamaPeminjaman(Integer.parseInt(lamaPinjam.getText()));
        peminjaman.setTanggalKembali(tanggal_kembali);
        peminjaman.setStatus(status.getSelectedItem().toString());
        
        PeminjamanController peminjamanController = new PeminjamanController();
        boolean hasil = peminjamanController.pinjamBuku(peminjaman);
        
        if(hasil){
            loadData();
            MessageUtil.success(this, "Berhasil Meminjam Buku");
            resetForm();
        }else{
            MessageUtil.error(this, "Gagal Meminjam Buku");
            resetForm();
        }
    }//GEN-LAST:event_addActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_resetActionPerformed

    private void lamaPinjamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamaPinjamKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();

        if (!Character.isDigit(c) 
            && c != java.awt.event.KeyEvent.VK_BACK_SPACE
            && c != java.awt.event.KeyEvent.VK_DELETE) {

            evt.consume();
        }
    }//GEN-LAST:event_lamaPinjamKeyTyped

    private void table_pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pinjamMouseClicked
        // TODO add your handling code here:
        cmbAnggota.setEnabled(false);
        cmbBuku.setEnabled(false);
        lamaPinjam.setEditable(false);
        
        int row = table_pinjam.getSelectedRow();
        if(row < 0){
            return;
        }
        
        int id_pinjam = Integer.parseInt(table_pinjam.getValueAt(row, 0).toString());
        PeminjamanController peminjamanController = new PeminjamanController();
        Peminjaman peminjaman = peminjamanController.getPeminjamanById(id_pinjam);
        BukuController bukuController = new BukuController();
        AnggotaController anggotaController = new AnggotaController();
        Anggota anggota = anggotaController.getMemberById(peminjaman.getIdAnggota());
        Buku buku = bukuController.getBukuById(peminjaman.getIdBuku());
        
        if(peminjaman != null){
            idPinjam.setText(String.valueOf(peminjaman.getIdPinjam()));
            cmbAnggota.setSelectedItem(anggota.getUsername());
            cmbBuku.setSelectedItem(buku.getJudulBuku());
            tanggalPinjam.setText(peminjaman.getTanggalPinjam());
            lamaPinjam.setText(String.valueOf(peminjaman.getLamaPeminjaman()));
            status.setSelectedItem(peminjaman.getStatus());
        }
    }//GEN-LAST:event_table_pinjamMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Peminjaman peminjaman = new Peminjaman();
        PeminjamanController peminjamanController = new PeminjamanController();
        
        if(idPinjam.getText().isEmpty()){
            MessageUtil.warning(this, "Silahkan Pilih Data Yang ingin Dihapus");
            return;
        }
        int confirm
                = MessageUtil.confirm(
                        this,
                        "Hapus peminjaman ini?"
                );

        if (confirm
                != JOptionPane.YES_OPTION) {

            return;
        }
        
        peminjaman.setIdPinjam(Integer.parseInt(idPinjam.getText()));
        boolean hasil = peminjamanController.hapusPeminjaman(peminjaman.getIdPinjam());
        if(hasil){
            loadData();
            MessageUtil.success(this, "Data Berhasil Dihapus");
            resetForm();
        }else{
            MessageUtil.error(this, "Data Gagal Dihapus");
            resetForm();
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BorrowView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbAnggota;
    private javax.swing.JComboBox<String> cmbBuku;
    private javax.swing.JButton delete;
    private javax.swing.JTextField idPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lamaPinjam;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable table_pinjam;
    private javax.swing.JTextField tanggalPinjam;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
